# Generated by Django 3.0.7 on 2020-06-20 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0005_empleado_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='full_name',
        ),
    ]
